objc_library(
    name = "ObjcModule",
    module_name = "ObjcModule",
    enable_modules = True,
    hdrs = ["ObjCModule.h"],
    srcs = ["ObjCModule.m"],
    includes = ["ObjCModule.h"],
    sdk_frameworks = [
        "Foundation",
    ],
    visibility = ["//visibility:public"],
)

# objc_import(
#     name = "libsignal_ffi_lib",
#     # hdrs = ["libsignal/SignalFfi/signal_ffi.h"],
#     archives = ["@libsignal//:libsignal_ffi"],
#     visibility = ["//visibility:public"],
# )


